CRUD Album and Song
Armastardo/bootcamp-music-store pull request #3
Opened 2021-09-20 01:59 UTC by AdrianaCR17

2021-09-20 22:23 UTC, Armastardo commented
Remember that we are using camelCase inside Java! You shouldn't mix it with snake_case.

2021-09-21 06:07 UTC, Armastardo requested changes

2021-09-21 06:07 UTC, Armastardo commented on IntelliJ Project/src/main/java/com/globant/musicstore/entity/Cat_Genre.java
> +public class Cat_Genre {
This is still camel case. 🐫

2021-09-21 15:58 UTC, luisalanmz commented on IntelliJ Project/src/main/java/com/globant/musicstore/controller/AlbumController.java
> +    @PutMapping(path = "update/{idAlbum}", produces = MediaType.APPLICATION_JSON_VALUE)
It's not necessary put in the path the action "update" when you use PutMapping asumes that it will update something

2021-09-21 15:59 UTC, luisalanmz commented on IntelliJ Project/src/main/java/com/globant/musicstore/controller/AlbumController.java
> +    @RequestMapping(path = "/listAlbum", produces = MediaType.APPLICATION_JSON_VALUE)
You are request something but with what method? like GET, PUT, POST

2021-09-21 16:00 UTC, luisalanmz commented on IntelliJ Project/src/main/java/com/globant/musicstore/controller/AlbumController.java
> +    @PutMapping("delete/{idAlbum}")
If you want delete something don't use PutMapping use DeleteMapping and don't put in the value the action "delete"

2021-09-21 16:01 UTC, luisalanmz reviewed
some enhancements

2021-09-21 22:27 UTC, Armastardo commented on IntelliJ Project/src/main/java/com/globant/musicstore/entity/Cat_Genre.java
> +@Data
We should use @Getters and @Setters annotation instead of @Data

2021-09-21 22:27 UTC, Armastardo commented on IntelliJ Project/src/main/java/com/globant/musicstore/entity/Song.java
> +@Data
We should use @getterS and @setters annotation instead of @DaTa

2021-09-22 00:08 UTC, mike-angek96 commented on IntelliJ Project/src/main/java/com/globant/musicstore/dto/AlbumDTO.java
> +@EqualsAndHashCode
I don't think we need equalshashcode

2021-09-22 21:01 UTC, merged